# SmashSumo configuration
# Versioning number, do not change
version: 110

# !! If any settings here are invalid, they will be set to their default options !!

# Lobby location (player is teleported to after game ends)
# You can set this in-game by typing /ss config lobby
lobby:
# What gamemode to switch players to after leaving a game (CREATIVE, SURVIVAL, ADVENTURE, SPECTATOR; default: ADVENTURE)
lobby-gamemode: ADVENTURE
# Whether to force an empty inventory before being able to join a game (default: true)
# The game will clear your inventories regardless if this is enabled or not, hence it is enabled by default
force-empty-inventory: true

# Game Options
game:
  # The number of lives a person has (default: 3)
  lives: 3
  # Whether to allow placing and breaking blocks (default: false)
  # Arena restoring is not supported
  allow-block: false
  # How long it should take for the player to respawn (multiple of 50ms, minimum: 100, default: 1000)
  respawn-time: 1000
  # How long it should take for the respawn platform to automatically despawn (multiple of 50ms, default: 3000)
  platform-despawn-time: 3000
  # The name of the kit all players will have by default, if this is null no kit will be given (default: null)
  default-kit: null
  # Knockback settings
  knockback:
    # Base vertical knockback (default: 0.5)
    initial-y: 0.5
    # Minimum knockback size (default: 1.1)
    minimum-size: 1.1
    # Horizontal damage knockback multiplier (default: 0.033)
    xz-damage-multiplier: 0.033
    # Vertical damage knockback multiplier (default: 0.025)
    y-damage-multiplier: 0.025
    # Horizontal momentum knockback multiplier (default: 1)
    xz-momentum-multiplier: 1
    # Vertical momentum knockback multiplier (default: 0.9)
    y-momentum-multiplier: 0.9
    # Number of ticks required between hits (default: 8)
    no-damage-ticks: 8


# Styling options (legacy color - case-sensitive, see https://helpch.at/docs/1.8.8/org/bukkit/ChatColor.html)
style:
  # Primary color (default: DARK_AQUA)
  primary-color: DARK_AQUA
  # Secondary color (default: AQUA)
  secondary-color: AQUA
  # Team colors (specify any number of them and they'll be used in rotation)
  # (default: RED, BLUE, YELLOW, GREEN, AQUA, WHITE, LIGHT_PURPLE, GRAY)
  team-colors:
    - RED
    - BLUE
    - YELLOW
    - GREEN
    - AQUA
    - WHITE
    - LIGHT_PURPLE
    - GRAY