# SmashSumo configuration
# marukyuu, 14/11/2025

# Versioning number, do not change
version: 2

# Lobby location (player is teleported to after game ends)
# You can set this in-game by typing /ss config lobby
lobby:

# Whether to force an empty inventory before being able to join a game (default: false)
force-empty-inventory: false

# Game Options
game:
  # The number of lives a person has (default: 3)
  lives: 3
  # Whether to allow placing and breaking blocks (default: false)
  # Arena restoring is not supported
  allow-block: false
  # How long it should take for the player to respawn (multiple of 50msm, minimum: 100, default: 1000)
  respawn-time: 1000
  # How long it should take for the respawn platform to automatically despawn (multiple of 50ms, default: 3000)
  platform-despawn-time: 3000
  # Knockback settings
  knockback:
    # Base vertical knockback (default: 0.5)
    initial-y: 0.5
    # Minimum knockback size (default: 1.1)
    minimum-size: 1.1
    # Horizontal damage knockback multiplier (default: 0.033)
    xz-damage-multiplier: 0.033
    # Vertical damage knockback multiplier (default: 0.025)
    y-damage-multiplier: 0.025
    # Horizontal momentum knockback multiplier (default: 1)
    xz-momentum-multiplier: 1
    # Vertical momentum knockback multiplier (default: 0.9)
    y-momentum-multiplier: 0.9


# Styling options (legacy color - case-sensitive, see https://helpch.at/docs/1.8.8/org/bukkit/ChatColor.html)
style:
  # Primary color (default: DARK_AQUA)
  primary-color: DARK_AQUA
  # Secondary color (default: AQUA)
  secondary-color: AQUA
  # Team colors (specify any number of them and they'll be used in rotation)
  # (default: RED, BLUE, YELLOW, GREEN, AQUA, WHITE, LIGHT_PURPLE, GRAY)
  team-colors:
    - RED
    - BLUE
    - YELLOW
    - GREEN
    - AQUA
    - WHITE
    - LIGHT_PURPLE
    - GRAY